/* tslint:disable */
/* eslint-disable */
/**
 * Volcani Agent Server
 * Agentic API Server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * Arguments for the tool call
 * @export
 * @interface Args
 */
export interface Args {
}
/**
 * A block with type and content.
 * @export
 * @interface Block
 */
export interface Block {
    /**
     * Unique identifier for the block
     * @type {string}
     * @memberof Block
     */
    'id': string;
    /**
     * Type of the block (markdown, component, tool_call_request, tool_call_response, etc.)
     * @type {string}
     * @memberof Block
     */
    'type': string;
    /**
     * 
     * @type {Content}
     * @memberof Block
     */
    'content': Content | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Block
     */
    'metadata'?: { [key: string]: any; } | null;
}
/**
 * Schema definition for a block type.
 * @export
 * @interface BlockSchema
 */
export interface BlockSchema {
    /**
     * Name of the block
     * @type {string}
     * @memberof BlockSchema
     */
    'name': string;
    /**
     * Block type identifier
     * @type {string}
     * @memberof BlockSchema
     */
    'type': string;
    /**
     * Description of what the block does
     * @type {string}
     * @memberof BlockSchema
     */
    'description': string;
    /**
     * JSON Schema for expected data to render the block
     * @type {{ [key: string]: any; }}
     * @memberof BlockSchema
     */
    'data_schema': { [key: string]: any; };
}
/**
 * A single chat message in the conversation history.
 * @export
 * @interface ChatMessage
 */
export interface ChatMessage {
    /**
     * Unique message identifier
     * @type {string}
     * @memberof ChatMessage
     */
    'message_id': string;
    /**
     * Session identifier
     * @type {string}
     * @memberof ChatMessage
     */
    'session_id': string;
    /**
     * When the message was sent
     * @type {string}
     * @memberof ChatMessage
     */
    'timestamp': string;
    /**
     * Role: \'user\', \'assistant\', or \'system\'
     * @type {string}
     * @memberof ChatMessage
     */
    'role': string;
    /**
     * 
     * @type {Array<Block>}
     * @memberof ChatMessage
     */
    'blocks'?: Array<Block> | null;
    /**
     * Additional message metadata
     * @type {{ [key: string]: any; }}
     * @memberof ChatMessage
     */
    'metadata'?: { [key: string]: any; };
}
/**
 * Response model for session messages.
 * @export
 * @interface ChatMessagesResponse
 */
export interface ChatMessagesResponse {
    /**
     * Session identifier
     * @type {string}
     * @memberof ChatMessagesResponse
     */
    'session_id': string;
    /**
     * User identifier
     * @type {string}
     * @memberof ChatMessagesResponse
     */
    'user_id': string;
    /**
     * List of messages in the session
     * @type {Array<ChatMessage>}
     * @memberof ChatMessagesResponse
     */
    'messages': Array<ChatMessage>;
    /**
     * Total number of messages in the session
     * @type {number}
     * @memberof ChatMessagesResponse
     */
    'total_messages': number;
    /**
     * Always False - no pagination
     * @type {boolean}
     * @memberof ChatMessagesResponse
     */
    'has_more': boolean;
    /**
     * Total message count only
     * @type {{ [key: string]: any; }}
     * @memberof ChatMessagesResponse
     */
    'pagination': { [key: string]: any; };
}
/**
 * Session data for sidebar display.
 * @export
 * @interface ChatSession
 */
export interface ChatSession {
    /**
     * Session identifier
     * @type {string}
     * @memberof ChatSession
     */
    'session_id': string;
    /**
     * Session name (generated from first message)
     * @type {string}
     * @memberof ChatSession
     */
    'name': string;
    /**
     * User identifier
     * @type {string}
     * @memberof ChatSession
     */
    'user_id': string;
    /**
     * 
     * @type {string}
     * @memberof ChatSession
     */
    'created_at'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChatSession
     */
    'updated_at'?: string | null;
    /**
     * Number of messages in the session
     * @type {number}
     * @memberof ChatSession
     */
    'message_count': number;
    /**
     * Preview of the last message
     * @type {string}
     * @memberof ChatSession
     */
    'last_message_preview': string;
}
/**
 * Response model for sidebar sessions.
 * @export
 * @interface ChatSessionResponse
 */
export interface ChatSessionResponse {
    /**
     * User identifier
     * @type {string}
     * @memberof ChatSessionResponse
     */
    'user_id': string;
    /**
     * List of sessions for sidebar
     * @type {Array<ChatSession>}
     * @memberof ChatSessionResponse
     */
    'sessions': Array<ChatSession>;
    /**
     * Total number of sessions available
     * @type {number}
     * @memberof ChatSessionResponse
     */
    'total_sessions': number;
    /**
     * Whether there are more sessions available
     * @type {boolean}
     * @memberof ChatSessionResponse
     */
    'has_more': boolean;
    /**
     * Pagination information
     * @type {{ [key: string]: any; }}
     * @memberof ChatSessionResponse
     */
    'pagination': { [key: string]: any; };
}
/**
 * Content data for the block
 * @export
 * @interface Content
 */
export interface Content {
    /**
     * ID of the tool call
     * @type {string}
     * @memberof Content
     */
    'tool_call_id': string;
    /**
     * Name of the tool call
     * @type {string}
     * @memberof Content
     */
    'name': string;
    /**
     * 
     * @type {Args}
     * @memberof Content
     */
    'args'?: Args;
    /**
     * Result content of the tool call
     * @type {{ [key: string]: any; }}
     * @memberof Content
     */
    'result_content': { [key: string]: any; };
    /**
     * Whether the tool call failed
     * @type {boolean}
     * @memberof Content
     */
    'is_tool_call_error': boolean;
    /**
     * Time taken to call the tool
     * @type {number}
     * @memberof Content
     */
    'total_response_time': number;
}
/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * Request model for agent invocation.
 * @export
 * @interface InvokeRequest
 */
export interface InvokeRequest {
    /**
     * Natural language query
     * @type {string}
     * @memberof InvokeRequest
     */
    'query': string;
    /**
     * 
     * @type {string}
     * @memberof InvokeRequest
     */
    'session_id'?: string | null;
    /**
     * 
     * @type {Array<BlockSchema>}
     * @memberof InvokeRequest
     */
    'client_capabilities'?: Array<BlockSchema> | null;
}
/**
 * Response model for agent invocation.
 * @export
 * @interface InvokeResponse
 */
export interface InvokeResponse {
    /**
     * Session identifier
     * @type {string}
     * @memberof InvokeResponse
     */
    'session_id': string;
    /**
     * 
     * @type {string}
     * @memberof InvokeResponse
     */
    'trace_id'?: string | null;
    /**
     * List of blocks with type and content
     * @type {Array<Block>}
     * @memberof InvokeResponse
     */
    'blocks': Array<Block>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof InvokeResponse
     */
    'user_context'?: { [key: string]: any; } | null;
}
/**
 * 
 * @export
 * @interface LocationInner
 */
export interface LocationInner {
}
/**
 * Response model for session suggestion queries.
 * @export
 * @interface SuggestionsResponse
 */
export interface SuggestionsResponse {
    /**
     * List of suggestions for possible next user queries based on the previous query
     * @type {Array<string>}
     * @memberof SuggestionsResponse
     */
    'suggestions': Array<string>;
}
/**
 * 
 * @export
 * @interface ToolCallRequestContent
 */
export interface ToolCallRequestContent {
    /**
     * ID of the tool call
     * @type {string}
     * @memberof ToolCallRequestContent
     */
    'tool_call_id': string;
    /**
     * Name of the tool call
     * @type {string}
     * @memberof ToolCallRequestContent
     */
    'name': string;
    /**
     * 
     * @type {Args}
     * @memberof ToolCallRequestContent
     */
    'args'?: Args;
}
/**
 * 
 * @export
 * @interface ToolCallResponseContent
 */
export interface ToolCallResponseContent {
    /**
     * ID of the tool call
     * @type {string}
     * @memberof ToolCallResponseContent
     */
    'tool_call_id': string;
    /**
     * Name of the tool call
     * @type {string}
     * @memberof ToolCallResponseContent
     */
    'name': string;
    /**
     * Result content of the tool call
     * @type {{ [key: string]: any; }}
     * @memberof ToolCallResponseContent
     */
    'result_content': { [key: string]: any; };
    /**
     * Whether the tool call failed
     * @type {boolean}
     * @memberof ToolCallResponseContent
     */
    'is_tool_call_error': boolean;
    /**
     * Time taken to call the tool
     * @type {number}
     * @memberof ToolCallResponseContent
     */
    'total_response_time': number;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<LocationInner>}
     * @memberof ValidationError
     */
    'loc': Array<LocationInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get all messages for a specific session.
         * @summary Get Session Messages
         * @param {string} sessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSessionMessagesApiSessionsSessionIdMessagesGet: async (sessionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('getSessionMessagesApiSessionsSessionIdMessagesGet', 'sessionId', sessionId)
            const localVarPath = `/api/sessions/{session_id}/messages`
                .replace(`{${"session_id"}}`, encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get suggestions for a specific session.
         * @summary Get Session Suggestions
         * @param {string} sessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSessionSuggestionsApiSessionsSessionIdSuggestionsGet: async (sessionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('getSessionSuggestionsApiSessionsSessionIdSuggestionsGet', 'sessionId', sessionId)
            const localVarPath = `/api/sessions/{session_id}/suggestions`
                .replace(`{${"session_id"}}`, encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the current status of the agent.
         * @summary Get Status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatusStatusGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get sessions for sidebar with names and message counts.
         * @summary Get User Sessions
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserSessionsApiSessionsGet: async (limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sessions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Health check endpoint that doesn\'t require authentication.
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Invoke the deployed agent with a natural language query.
         * @summary Invoke Agent
         * @param {InvokeRequest} invokeRequest 
         * @param {string} [accept] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invokeAgentInvokePost: async (invokeRequest: InvokeRequest, accept?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'invokeRequest' is not null or undefined
            assertParamExists('invokeAgentInvokePost', 'invokeRequest', invokeRequest)
            const localVarPath = `/invoke`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (accept != null) {
                localVarHeaderParameter['accept'] = String(accept);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(invokeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Get all messages for a specific session.
         * @summary Get Session Messages
         * @param {string} sessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSessionMessagesApiSessionsSessionIdMessagesGet(sessionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChatMessagesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSessionMessagesApiSessionsSessionIdMessagesGet(sessionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getSessionMessagesApiSessionsSessionIdMessagesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get suggestions for a specific session.
         * @summary Get Session Suggestions
         * @param {string} sessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSessionSuggestionsApiSessionsSessionIdSuggestionsGet(sessionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuggestionsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSessionSuggestionsApiSessionsSessionIdSuggestionsGet(sessionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getSessionSuggestionsApiSessionsSessionIdSuggestionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get the current status of the agent.
         * @summary Get Status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStatusStatusGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStatusStatusGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getStatusStatusGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get sessions for sidebar with names and message counts.
         * @summary Get User Sessions
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserSessionsApiSessionsGet(limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChatSessionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserSessionsApiSessionsGet(limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getUserSessionsApiSessionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Health check endpoint that doesn\'t require authentication.
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheckHealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheckHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.healthCheckHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Invoke the deployed agent with a natural language query.
         * @summary Invoke Agent
         * @param {InvokeRequest} invokeRequest 
         * @param {string} [accept] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async invokeAgentInvokePost(invokeRequest: InvokeRequest, accept?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InvokeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.invokeAgentInvokePost(invokeRequest, accept, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.invokeAgentInvokePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Get all messages for a specific session.
         * @summary Get Session Messages
         * @param {string} sessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSessionMessagesApiSessionsSessionIdMessagesGet(sessionId: string, options?: RawAxiosRequestConfig): AxiosPromise<ChatMessagesResponse> {
            return localVarFp.getSessionMessagesApiSessionsSessionIdMessagesGet(sessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get suggestions for a specific session.
         * @summary Get Session Suggestions
         * @param {string} sessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSessionSuggestionsApiSessionsSessionIdSuggestionsGet(sessionId: string, options?: RawAxiosRequestConfig): AxiosPromise<SuggestionsResponse> {
            return localVarFp.getSessionSuggestionsApiSessionsSessionIdSuggestionsGet(sessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the current status of the agent.
         * @summary Get Status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatusStatusGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getStatusStatusGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Get sessions for sidebar with names and message counts.
         * @summary Get User Sessions
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserSessionsApiSessionsGet(limit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<ChatSessionResponse> {
            return localVarFp.getUserSessionsApiSessionsGet(limit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * Health check endpoint that doesn\'t require authentication.
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.healthCheckHealthGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Invoke the deployed agent with a natural language query.
         * @summary Invoke Agent
         * @param {InvokeRequest} invokeRequest 
         * @param {string} [accept] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invokeAgentInvokePost(invokeRequest: InvokeRequest, accept?: string, options?: RawAxiosRequestConfig): AxiosPromise<InvokeResponse> {
            return localVarFp.invokeAgentInvokePost(invokeRequest, accept, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Get all messages for a specific session.
     * @summary Get Session Messages
     * @param {string} sessionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getSessionMessagesApiSessionsSessionIdMessagesGet(sessionId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getSessionMessagesApiSessionsSessionIdMessagesGet(sessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get suggestions for a specific session.
     * @summary Get Session Suggestions
     * @param {string} sessionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getSessionSuggestionsApiSessionsSessionIdSuggestionsGet(sessionId: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getSessionSuggestionsApiSessionsSessionIdSuggestionsGet(sessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get the current status of the agent.
     * @summary Get Status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getStatusStatusGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getStatusStatusGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get sessions for sidebar with names and message counts.
     * @summary Get User Sessions
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getUserSessionsApiSessionsGet(limit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getUserSessionsApiSessionsGet(limit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Health check endpoint that doesn\'t require authentication.
     * @summary Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public healthCheckHealthGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).healthCheckHealthGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Invoke the deployed agent with a natural language query.
     * @summary Invoke Agent
     * @param {InvokeRequest} invokeRequest 
     * @param {string} [accept] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public invokeAgentInvokePost(invokeRequest: InvokeRequest, accept?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).invokeAgentInvokePost(invokeRequest, accept, options).then((request) => request(this.axios, this.basePath));
    }
}



